### POST Request ###

POST http://192.168.174.21:3000/absen
 Content-Type: application/json

{
  "id_user": "8acf589d-4b56-11ee-9762-0242ac120002",
  "id_jenis_absen": 1,
  "id_lokasi": 1
}

### GET Request ###

GET http://192.168.174.21:3000/history

### POST REGISTER ###
POST http://192.168.174.21:3000/register
Content-Type: application/json

{
  "username": "cek",
  "password": "cek",
  "id_role": 1,
  "nik": 75011324,
  "user_image":"picture.jpg"
}


### POST LOGIN ###

POST http://192.168.174.21:3000/login

{
  "username": "minjeey",
  "password": "minjeey"
}

