### POST Request ###

POST http://192.168.22.21:3000/absen
 Content-Type: application/json

{
  "id_user": "60f79908-c641-40b4-8e5d-a9a88f3d3d5d",
  "id_jenis_absen": 2,
  "id_lokasi": "ec04cf67-4ea5-11ee-a5b4-0242ac120002",
  "latitude":0.719395,
  "longitude":122.532529
}

### GET Request ###

GET http://192.168.22.21:3000/history/60f79908-c641-40b4-8e5d-a9a88f3d3d5d 	

### POST REGISTER ###
POST http://192.168.123.21:3000/register
Content-Type: multipart/form-data

{
  "username": "cek",
  "password": "cek",
  "id_role": 1,
  "nik": 75011324,
  "user_image":"picture.jpg"
}


### POST LOGIN ###

POST http://192.168.22.21:3000/login
 Content-Type: application/json

{
  "username": "lamin",
  "password": "lamin"
}

